let
    // Read parameters from Parameters table
    ParametersTable = Excel.CurrentWorkbook(){[Name="Parameters"]}[Content],
    
    // Extract Year parameter (from "Value" column, first row)
    YearValue = if Table.HasColumns(ParametersTable, "Value") and Table.RowCount(ParametersTable) > 0 
                then Text.Trim(ParametersTable{0}[Value]) 
                else "2025",
    
    // Extract SubjectCodes parameter (from "Value" column, second row)
    SubjectCodesText = if Table.HasColumns(ParametersTable, "Value") and Table.RowCount(ParametersTable) > 1 
                       then Text.Trim(ParametersTable{1}[Value]) 
                       else "",
    SubjectCodesList = if SubjectCodesText = "" then {} else List.Transform(Text.Split(SubjectCodesText, ","), each Text.Trim(_)),
    
    BaseUrl = "https://handbook.unimelb.edu.au/" & YearValue & "/subjects/",
    
    // Function to fetch and parse HTML for each subject
    FetchSubjectHTML = (subjectCode as text) as record =>
        let
            LowerCode = Text.Lower(Text.Trim(subjectCode)),
            Url = BaseUrl & LowerCode & "/assessment",
            TryFetch = try
                let
                    SourceHtml = Text.FromBinary(Web.Contents(Url)),
                    TableStartDelimiter = "<div class=""assessment-table"">",
                    TableStartPosition = Text.PositionOf(SourceHtml, TableStartDelimiter),
                    IsolatedTableHtml = if TableStartPosition > -1 then
                        let
                            FromStart = Text.Range(SourceHtml, TableStartPosition),
                            LargeChunk = Text.Start(FromStart, 10000),
                            TableEnd = Text.PositionOf(LargeChunk, "</table>"),
                            AfterTable = if TableEnd > -1 then Text.Range(LargeChunk, TableEnd) else LargeChunk,
                            NextDivEnd = Text.PositionOf(AfterTable, "</div>"),
                            FinalHtml = if NextDivEnd > -1 then Text.Start(LargeChunk, TableEnd + NextDivEnd + 6) else LargeChunk
                        in
                            FinalHtml
                    else
                        "",
                    ExtractedHtml = IsolatedTableHtml
                in
                    ExtractedHtml
            otherwise null,
            Result = if TryFetch <> null and Text.Length(TryFetch) > 100 then
                [SubjectCode = Text.Upper(subjectCode), URL = Url, AssessmentTableHTML = TryFetch,
                 HTMLLength = Text.Length(TryFetch), Status = "Success", ErrorMessage = null, FetchTime = DateTime.LocalNow()]
            else
                [SubjectCode = Text.Upper(subjectCode), URL = Url, AssessmentTableHTML = TryFetch,
                 HTMLLength = if TryFetch <> null then Text.Length(TryFetch) else 0, Status = "Failed",
                 ErrorMessage = if TryFetch = null then "Could not fetch URL" else "Assessment table not found or too short",
                 FetchTime = DateTime.LocalNow()]
        in
            Result,
    
    // Process all subject codes (if none supplied, empty list)
    ProcessedData = List.Transform(SubjectCodesList, each FetchSubjectHTML(_)),
    
    // Convert list of records to table
    ResultTable = Table.FromRecords(ProcessedData)
in
    ResultTable